### PR TITLE
Switch statement

### PR DESCRIPTION
**Pull request by mrmlnc**
## Proposed Changes

Source: #33 

## Types of Changes

- [x] Feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) guide
- [x] Lint and unit tests pass with my changes
- [x] I have added tests that prove my fix is effective/works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes are merged and published in downstream modules

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
👍 Cool 😎 , I take a deeper look at it later/until tomorrow, I'm on mobile atm.

**Comment by michael-ciniawsky** [comment]
👍

**Comment by mrmlnc** [comment]
@michael-ciniawsky, how to I can get green light for Coveralls?

**Comment by michael-ciniawsky** [comment]
@mrmlnc  hmmm... 😛 L251,322,329 (switch errors) are shown as uncovered, but they are definitely tested. I don't know tbh, as long as it works we simply don't mind for now 👀 ?

**Pull request merged**
