### PR TITLE
feat: allow script locals to use global locals

### PR DESCRIPTION
**Pull request by juliovedovatto**
## Proposed Changes

The intent of this PR is to add support to allow script locals to use global locals defined.

I faced a situation simular to https://github.com/posthtml/posthtml-expressions/issues/132, where I needed to access a global value from my template file, while using the `posthtml-include` plugin.

Example:

```js
posthtml({
      plugins: [
        include({ posthtmlExpressionsOptions: { 
         removeScriptLocals: true, 
         locals: {}
       })
      ],
})
```

```html
<!-- src/components/ordered-list.html -->
<script locals>
  module.exports = {
    start: locals?.props?.startAt || 1,
  }
</script>

<div class="w-full ordered-list">
  <each loop="item, index in (props.list || [])">
    <p
      class="border-b-2 border-gray-400 font-stabil font-medium uppercase pb-1 sm:pb-3 3xl:pb-4">
      <span class="text-sm"> ({{ start++ }}) </span>
      <span class="text-left"> {{ item }} </span>
    </p>
  </each>
</div>
```

```html
<include src="src/components/ordered-list.html">
{
  "props": {
    "list": [
      "activista la",
      "activista la",
    ],
    "startAt": 10
  }
}
</include>
```

Generated output:

```html
<div class="w-full ordered-list">
    <p class="border-b-2 border-gray-400 font-stabil font-medium uppercase pb-1 sm:pb-3 3xl:pb-4">
      <span class="text-sm"> (20) </span>
      <span class="text-left"> activista la </span>
    </p>
  
    <p class="border-b-2 border-gray-400 font-stabil font-medium uppercase pb-1 sm:pb-3 3xl:pb-4">
      <span class="text-sm"> (21) </span>
      <span class="text-left"> activista la </span>
    </p>
</div>
```

## Types of Changes

What types of changes does your code introduce
_Put an `x` in the boxes that apply_

- [ ] Bug (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature which changes existing functionality)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is a reminder of what we are going to look for before merging your
code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) guide
- [x] Lint and unit tests pass with my changes
- [x] I have added tests that prove my fix is effective/works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes are merged and published in downstream modules

## Further Comments

If this is a large or complex change, kick off the discussion by explaining why
you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by Scrum — APPROVED** [review]

**Comment by thewebartisan7** [comment]
@juliovedovatto I notice that using webpack + posthtml-loader, after HMR the locals are merged with previous locals used in the same extend/include or module file.

For example let's assume you have used a local inside extend:

```html
<script locals>
  module.exports = {
    foo: locals.foo || 'default bar',
  };
</script>
<!DOCTYPE html>
<html>
  <body>
            <block name="content"></block>
  </body>
</html>


```html
<extends src="layout.html" locals='{
  "foo": "bar",
}'>
  <block name="content">
    {{ foo }} is bar
  </block>
</extends>
```

In second page:

```html
<extends src="layout.html">
  <block name="content">
    {{ foo }} is bar again after HMR, but in first load is "default bar"
  </block>
</extends>
```

Any idea if am I missing something?

Thanks

**Comment by thewebartisan7** [comment]
@juliovedovatto if we here https://github.com/posthtml/posthtml-expressions/blob/master/lib/index.js#L164
change the order of options.locals and locals like below:

```js
return normalizeTree(clearRawTag(walk({ locals: { ...locals, ...options.locals }, strictMode: options.strictMode }, tree)), tree.options)
```

Then we could just pass default values in script locals like below.

```html
<script locals>
    module.exports = {
        title: 'Really default title',
    }
</script>
```

What do you think?

**Comment by Scrum** [comment]
```...locals, ...options.locals```
This order is more correct.

**Comment by thewebartisan7** [comment]
Yes I understand that it's better if you do something with locals inside the script, but in that case you can create new local, example:

```js
<script locals>
    const first = 'John';
    const last = 'Doe';

    module.exports = {
        firstName: first,
        lastName: last,
        fullName: (locals.firstName || first) + ' ' + (locals.lastName || last);
    }
</script>
```

But yes it's depend.. If you want just return always default or provided, then it's better do like now.

In my new component plugin I added both way where you can define if locals is overridden (default behavior) or if it's being used by locals script (named computed).

I will write more about it in next days.

**Pull request merged**
